# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.13"
  commands:
    - pip install -r docs/requirements.txt
    - pip install .
    - pip install pytest pytest-cov coverage-badge
    - pytest --cov=src/gatenet --cov-report=html
    - coverage-badge -o docs/source/_static/coverage.svg
    - mkdir -p docs/source/_static/htmlcov
    - cp -a htmlcov/. docs/source/_static/htmlcov/
    - sphinx-build -b html docs/source docs/build/html

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt
