site_name: gatenet
site_description: Python-first networking observation toolkit
site_url: https://clxrityy.github.io/gatenet

repo_name: clxrityy/gatenet
repo_url: https://github.com/clxrityy/gatenet

theme:
  font:
    text: Inter
    code: JetBrains Mono
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  manifest: assets/site.webmanifest
  palette:
    - scheme: slate
      primary: blue gray
      accent: deep purple

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - navigation.expand
    - content.code.copy
    - header.version_selector

extra:
  version:
    provider: mike

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed

extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_api_docs.py
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: true
            merge_init_into_class: true
            show_signature_annotations: true
            show_source: false
            heading_level: 2
            separate_signature: true

nav:
  - Home: index.md
  - Test Coverage: tests.md
  - API:
      - Overview: api/index.md
      - Reference:
        - cli:
            - api/gatenet/cli/__main__.md
            - api/gatenet/cli/discover.md
            - api/gatenet/cli/format.md
            - api/gatenet/cli/scan.md
        - core:
            - api/gatenet/core/models.md
        - discovery:
            - api/gatenet/discovery/aggregate.md
            - api/gatenet/discovery/arp.md
        - scan:
            - api/gatenet/scan/ports.md
