import json
from pathlib import Path

data = json.loads(Path("coverage.json").read_text())

total = data["totals"]
percent = total["percent_covered_display"]  # typically like "95"
statements = total["num_statements"]
missing = total["missing_lines"]

out = f"""
[//]: # (This file is auto-generated by scripts/coverage_summary.py)

# Test Coverage

<div class="stats-grid">

  <div class="stat-card" style="--pct: {percent}%;">
    <div class="stat-label">Total Coverage</div>
    <div class="stat-value">{percent}%</div>
    <div class="stat-bar" role="img" aria-label="Total coverage {percent} percent">
      <span></span>
    </div>
    <div class="stat-sub">Generated from <code>coverage.json</code></div>
  </div>

  <div class="stat-card">
    <div class="stat-label">Statements</div>
    <div class="stat-value">{statements}</div>
    <div class="stat-sub">Tracked executable statements</div>
  </div>

  <div class="stat-card stat-card--warn">
    <div class="stat-label">Missing</div>
    <div class="stat-value">{missing}</div>
    <div class="stat-sub">Statements not covered</div>
  </div>

</div>

<p class="stats-actions">
  <a href="coverage/index.html" class="md-button md-button--primary">View Coverage Report</a>
</p>
"""

Path("docs/tests.md").write_text(out.strip() + "\n")
