name: Upload Python Package to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Specify the Python version you want to use
      - name: Prepare requirements for Linux
        run: |
          # Remove macOS-only dependencies from requirements.txt for Linux builds
          grep -v 'pyobjc' requirements.txt > requirements.linux.txt
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.linux.txt
          pip install build
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python3 -m build
          twine upload dist/*
